let name = 'Mustafa';
let surname = 'Kamal';
let nickname = 'Ataturk';
let fullName = name + ' ' + surname + ' ' + nickname;
console.log(fullName);
console.log(fullName.length);
console.log(fullName.length-2);
console.log(fullName.includes('e'));
console.log(fullName.startsWith('code'));
console.log(fullName.endsWith('code'));
console.log(fullName.replaceAll('t','###'));
